version: 2
updates:
  - package-ecosystem: cargo
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'thursday'
      time: '02:00'
    open-pull-requests-limit: 10

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
